site_name: ERNIE Bot Agent
repo_url: https://github.com/PaddlePaddle/ERNIE-Bot-SDK/
repo_name: ERNIE-Bot-Agent
site_description: provides an easy-to-use Chinese agent builder tool suite.
copyright: '@PaddlePaddle community'
nav:
  - 快速开始:
    - 安装和鉴权: 'modules/preparation.md'
    - 构建一个简单智能体: 'modules/quickstart.md'
    - 使用 Tool: 'modules/tools/getting-started.md' 
  - 核心模块:
    - message: 'modules/message.md'
    - chat_models: 'modules/chat_models.md'
    - memory: 'modules/memory.md'
    - retrieval: 'modules/retrieval.md'
    - file: 'modules/file.md'
    - tools: 'modules/tools/create-tool.md'
  - API:
    - erniebot-agent:
      - agents: "package/erniebot_agent/agents.md"
      - chat_models: "package/erniebot_agent/chat_models.md"
      - file: "package/erniebot_agent/file.md"
      - message: "package/erniebot_agent/message.md"
      - memory: "package/erniebot_agent/memory.md"
      - retrieval: "package/erniebot_agent/retrieval.md"
      - tools: "package/erniebot_agent/tools.md"

theme:
  name: material
  favicon: img/favicon.png

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_bases: false
            show_root_heading: true
          paths: [erniebot-agent/src]
          selection:
            filters:
              - "^__init__$"  # but always include __init__ modules and methods
