site_name: Ernie Agent
repo_url: https://github.com/PaddlePaddle/ERNIE-Bot-SDK/
repo_name: ERNIE-Agent
site_description: provides an easy-to-use Chinese agent builder tool suite.
copyright: '@PaddlePaddle community'
nav:
  - 介绍: 'index.md'
  - 快速开始:
    - 介绍: 'tutorials/index.md' 
    - 使用 Tool: 'modules/tools/getting-started.md' 
  - 核心模块:
    - memory: 'modules/memory.md'
    - tools: 'modules/tools/create-tool.md'
  - API:
    - erniebot-agent:
      - agents: "package/erniebot_agent/agents.md"
      - memory: "package/erniebot_agent/memory.md"
      - tools: "package/erniebot_agent/tools.md"
      - chat_models: "package/erniebot_agent/chat_models.md"

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_bases: false
          paths: [erniebot-agent/src]
          selection:
            filters:
              - "^__init__$"  # but always include __init__ modules and methods
