site_name: ERNIE Bot Agent
repo_url: https://github.com/PaddlePaddle/ERNIE-Bot-SDK/
repo_name: ERNIE-Bot-Agent
site_description: provides an easy-to-use Chinese agent builder tool suite.
copyright: '@PaddlePaddle community'
nav:
  - 快速开始:
    - 安装和鉴权: 'modules/preparation.md'
    - 构建一个简单智能体: 'modules/quickstart.md'
    - 使用 Tool: 'modules/tools/getting-started.md' 
  - 教程:
    - Local Tool: "cookbooks/agent/local_tool.ipynb"
    - Remote Tool: "cookbooks/agent/remote_tool.ipynb"
  - 核心模块:
    - message: 'modules/message.md'
    - chat_models: 'modules/chat_models.md'
    - memory: 'modules/memory.md'
    - retrieval: 'modules/retrieval.md'
    - file: 'modules/file.md'
    - tools: 'modules/tools/create-tool.md'
  - API Referene:
    - erniebot-agent:
      - agents: "package/erniebot_agent/agents.md"
  - ERNIE-Bot-SDK:
    - 使用文档:
      - 预备步骤:
        - sdk/README.md
        - sdk/installation.md
        - sdk/authentication.md
        - sdk/configuration.md
        - sdk/models.md
      - 使用指南:
        - sdk/guides/chat_completion.md
        - sdk/guides/embedding.md
        - sdk/guides/image.md
        - sdk/guides/function_calling.md
    - API文档:
      - sdk/api_reference/chat_completion.md
      - sdk/api_reference/embedding.md
      - sdk/api_reference/image.md

theme:
  name: material
  favicon: img/favicon.png
  features:
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - admonition
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - toc:
      permalink: true


plugins:
  - search
  - mkdocs-jupyter:
      ignore_h1_titles: True
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_bases: false
            show_root_heading: true
          paths: [erniebot-agent/src]
          selection:
            filters:
              - "^__init__$"  # but always include __init__ modules and methods
