site_name: Ernie Agent
repo_url: https://github.com/PaddlePaddle/ERNIE-Bot-SDK/
repo_name: ERNIE-Agent
site_description: provides an easy-to-use Chinese agent builder tool suite.
copyright: '@PaddlePaddle community'
nav:
  - 介绍: 'index.md'
  - 快速开始:
    - 介绍: 'tutorials/index.md' 
  - 使用指南:
    - 介绍: 'how-to/how-to_introduction.md'
    - 安装: 'tutorials/installation.md'
    - 模型: 'tutorials/chat_models.md'
  - API:
    - erniebot-agent:
      - agents: "package/erniebot_agent/agents.md"
      - chat_models: "package/erniebot_agent/chat_models.md"

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_submodules: true
            docstring_style: google
            annotations_path: brief
          paths: [erniebot-agent/src]
          selection:
            filters:
              - "^__init__$"  # but always include __init__ modules and methods
